name: Build & Deploy Rails API

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: monehin/backend
      COMMIT_SHA: ${{ github.sha }}
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      KAMAL_REGISTRY_PASSWORD: ${{ secrets.KAMAL_REGISTRY_PASSWORD }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.2
          bundler-cache: true

      - name: Install correct Bundler version
        run: gem install bundler -v '~> 2.6'

      - name: Verify bundler version
        run: bundler -v

      - name: Install project gems
        working-directory: ./backend
        run: bundle install

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa
          ssh-keyscan 49.13.167.165 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy with Kamal
        working-directory: ./backend
        run: kamal deploy

